add healtcheck

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -31,6 +31,9 @@ jobs:
 
       - name: Install dependencies
         run: npm ci
+      
+      - name: Run linter
+        run: npm run lint
 
       - name: Start server
         run: |
@@ -169,7 +172,7 @@ jobs:
 
       - name: Start containers
         env:
-          # var env ale app-ului pentru smoke
+          
           MONGODB_CONNECTION_PROTOCOL: mongodb+srv
           MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
           MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
@@ -188,7 +191,7 @@ jobs:
             ${{ secrets.DOCKER_USERNAME }}/myapp:${TAG}
 
           docker run -d --name nginx --network appnet \
-            -p 8081:80 \
+            -p 8087:8087 \
             ${{ secrets.DOCKER_USERNAME }}/mynginx:${TAG}
 
       - name: Wait 60s and check status
@@ -206,6 +209,13 @@ jobs:
           else
             echo "✅ Toate containerele rulează OK"
           fi
+      - name: Healthcheck app
+        run: |
+          echo "🌐 Verific healthcheck la http://localhost:8080/health"
+          curl -sf http://localhost:8080/health || {
+            echo "❌ Healthcheck failed";
+            exit 1;
+          }
 
       - name: Cleanup
         if: always()
